### ISSUE TITLE
Attribute is not longer available after latest update

### ISSUE THREAD

**Issue by cboelter** [MetaModels/attribute_tabletext#11]
https://github.com/MetaModels/core/issues/734

**Comment by tim-bec** [comment]
Hier ebenso. Können wir das asap fixen? Das zerschießt mir grad kräftig die Installationen -.-

**Comment by cboelter** [comment]
Du kannst es mit dem PR von mir auch manuell fixen :)

**Comment by tim-bec** [comment]
pah. den merge ich einfach :) danke dir!

**Comment by tim-bec** [comment]
fixed with https://github.com/MetaModels/attribute_tabletext/commit/212e4c32d8efc252eb7b605c684192446a5f43f8 thanks @cboelter
