### ISSUE TITLE
FR: Ausgabe der Spaltenüberschriften

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_tabletext#14]
Es wäre schön, wenn (optional) die Spaltenüberschriften an die Frontend-Ausgabe durchgereicht werden.

**Comment by MacKP** [comment]
Was meinst du mit Spaltenüberschriften?

**Comment by zonky2** [comment]
add with PR https://github.com/MetaModels/attribute_tabletext/pull/18

**Comment by discordier** [comment]
In #18 they are NOT optionally but now always shown. I wonder if this is a good thing.
Can not tell as I never had this attribute used in production and therefore lack to see the usecase.

**Comment by zonky2** [comment]
Hmm... we can add a checkbox as "Hide headlines"

**Comment by discordier** [comment]
Rather add the checkbox "show headlines"?
We should use the setting used by most users.
@stefanheimes how do you guys use this?

**Comment by zonky2** [comment]
add feature in PR #20
