### ISSUE TITLE
Geleerte tabletext sind nicht leer

### ISSUE THREAD

**Issue by lucdesign** [MetaModels/attribute_tabletext#15]
Issue gewandert von bundle_attributes und translated_tabletext
https://github.com/MetaModels/attribute_translatedtabletext/issues/10

Wenn man eine tabletext einmal befüllt hat und dann alle Zeilen wieder löscht, bleibt eine "Geisterzeile" mit Leerstrings als Werten übrig. Im Template wird das als nicht-leeres Array erkannt und als leere Tabelle mit einer leeren Zeile ausgegeben.
Man kann diesen Fehler provisorisch mit der Abfrage

``` php
<?php if ($this->raw[0][0]['value'] !== "") : ?>
```

abfangen. Das gleiche muss man aber auch prüfen, wenn man die Zeilen zählen will!

**Comment by zonky2** [comment]
habe mir die Sache angesehen - aktuell wird für "jede Zelle" ein Datensatz angelegt - egal, ob mit Wert oder ohne
auch die "erste Standard-Zeile mit allen Zellen" wird automatisch gespeichert

Ziel wäre m.E. nur die Zellen zu speichern, die einen Wert haben - respektive die "geleerten Zellen" zu löschen und auch alle Zeilen ohne eine einzige gefüllte Zelle in der Eingabemaske zu löschen.

**Comment by zonky2** [comment]
add PR https://github.com/MetaModels/attribute_tabletext/pull/17

**Comment by zonky2** [comment]
fixed with PR #20
