### ISSUE TITLE
error if tabletext hidden in a sub palette

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_tabletext#22]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [x] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_tabletext/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |          |                                  |
| Contao version:                     |          |                                  |
| MetaModels version core:            |   a15       |                                  |
| MetaModels version attribute:       |          |                                  |
| Installation via composer:          | (yes) |                                  |
| Installed MetaModels packages:      |   bundle_all       |                                  |
| DCG version:                        |   b39       |                                  |

## Issue description

```
Warning: Invalid argument supplied for foreach() in composer/vendor/metamodels/attribute_tabletext/src/MetaModels/Attribute/TableText/TableText.php on line 127 
#0 composer/vendor/metamodels/attribute_tabletext/src/MetaModels/Attribute/TableText/TableText.php(127): __error(2, 'Invalid argumen...', '/data/wwwcust/r...', 127, Array)
#1 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(906): MetaModels\Attribute\TableText\TableText->setDataFor(Array)
#2 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(949): MetaModels\MetaModel->saveAttribute(Object(MetaModels\Attribute\TableText\TableText), Array, NULL, 'de')
#3 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(1031): MetaModels\MetaModel->updateVariants(Object(MetaModels\Item), 'de', Array, false)
#4 composer/vendor/metamodels/core/src/MetaModels/Item.php(340): MetaModels\MetaModel->saveItem(Object(MetaModels\Item))
#5 composer/vendor/metamodels/core/src/MetaModels/DcGeneral/Data/Driver.php(582): MetaModels\Item->save()
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(630): MetaModels\DcGeneral\Data\Driver->save(Object(MetaModels\DcGeneral\Data\Model))
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(725): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->doPersist()
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/EditHandler.php(76): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/View/ActionHandler/AbstractHandler.php(54): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\EditHandler->process()
#10 [internal function]: ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#12 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#13 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(152): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#14 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#15 system/modules/core/classes/Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#16 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_ca...')
#17 contao/main.php(20): Contao\BackendMain->run()
#18 {main}
```
## Steps to reproduce

1. make table text
2. set attribute table text in a sub palettes
3. hide per checkbox and save
4. change on of the other values of attributes and save

=> the method setDataFor (https://github.com/MetaModels/attribute_tabletext/blob/master/src/MetaModels/Attribute/TableText/TableText.php#L107) should "sleep" at save if tabletext hidden... but the `$arrValues` send a array with empty value e.g.

```
Array
(
    [93] => 
)
```

**Comment by discordier** [comment]
When a field is hidden the EditMask must not(!) send data to the model. That's the definition of the visible and edit conditions.
Therefore this is a bug in DCG.

**Comment by discordier** [comment]
After further investigation, this results from a correlation of DCG and core.

The DCG has no way to tell MetaModels which attributes are to be saved.
Further more, this information can also not be passed within `IMetaModel::save()` and hence all set attributes will get saved, even the invisible ones.

However, the value is not changed and therefore should be valid when they got retrieved for displaying the edit mask.

Can you please elaborate a little more how you got to that setup?
Is it a new item or editing an existing one?

Second, could you upgrade to latest versions beforehand? Your line `MetaModel.php(949)` in your stack trace is really on `MetaModel.php(961)` in current dev branch and shows a considerable offset.

**Comment by zonky2** [comment]
fixed with DCG 42 and Core a18
