### ISSUE TITLE
No functionality on new, duplicate, delete 

### ISSUE THREAD

**Issue by m-r-h-n** [MetaModels/attribute_tabletext#26]
## Checklist before I submit this issue report

I confirm that:
- [*] I have tested this with the latest version available
- [*] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [*] I have checked the Contao community forums for references https://community.contao.org/
- [*] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_tabletext/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                                  |7                                  |
| Contao version:                     | 3.5.28          |                                  |
| MetaModels version core:      |      2.0.0-alpha16          |                                  |
| MetaModels version attribute:   |    2.0.0          |                                  |
| Installation via composer:          | no                                  |
| Installed MetaModels packages:   |   nightly          |                                  |
| DCG version:                    |    2.0.0-beta40          |                                  |

## Issue description

No New Fields…
No Sorting…
No Delete…
… via Backend
If I do this directly in the database it still shows up but no funtionality via backend.
No JS errors are shown

**Comment by zonky2** [comment]
update MCW to dev-master https://github.com/menatwork/MultiColumnWizard/pull/228
