### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/attribute_tabletext#3]
We should add a array cast in all templates for the "foreach". Without an array cast we will get a warning, if we have no data.

**Comment by lucdesign** [comment]
That fits https://github.com/MetaModels/attribute_tabletext/issues/15
(as imho empty tables should be represented by arrays of length 0)

**Comment by discordier** [comment]
Warnings are bad, promoting to bug therefore.

**Comment by zonky2** [comment]
PR https://github.com/MetaModels/attribute_tabletext/pull/18
